extends: "@istanbuljs/nyc-config-typescript"
all: true
include: src
exclude:
  - "**/*.spec.ts"
watermarks:
  lines: 90
  functions: 90
  branches: 90
  statements: 90
reporter:
  - text
  - lcovonly
